### ISSUE TITLE
hemispheric projection + coordinate change = white background bug?

### ISSUE THREAD

**Issue by thinkin3d** [ofrohn/d3-celestial#25] opened 2018-12-02 07:35 UTC
Hello,

I have been trying to debug an interaction of features unsuccessfully for the past few days.  It appears to only apply to hemispheric projections, as far as I have noticed.  It is able to be demonstrated with the viewer:

https://ofrohn.github.io/celestial-demo/viewer.html

1) After page load, change the projection from 'Aitoff' to any projection with '(hemi)' in the title.  The chart background should remain black.
2) Change the coordinate system from 'Equatorial' to any other.  The chart will refresh with a white background, a little bit more zoomed in, and with a black vertical bar down the center.

I still don't have much visibility into the issue after trying to perform a trace through the code, but it seems that the styling is not being applied after a hemispheric re-projection / coordinate change.  Perhaps there is some silent error and the subsequent code that would apply styling isn't running?

Is there something else to this case that I am not understanding?

**Comment by genghisken** [comment] 2019-07-23 10:53
Hi all - I'm having the same issue. It seems to be a Safari-only problem when setting hemispheric projections.  (All other projections work fine with chosen background.)  The background gets set to transparent for some reason.  Chrome & Firefox render it OK.  Any ideas?

**Comment by ofrohn** [comment] 2019-07-24 14:45
I can't properly test Safari but I may have found a solution. It  seems that safari doesn't like js values like element.innerWidth in some situations, so I replaced it with  element.getBoundingClientRect().width.

Could somebody test the latest version (0.6.12)?

**Comment by genghisken** [comment] 2019-07-24 16:14
Many thanks for your speedy response.  I tested 0.6.12, but, alas, I still have the same issue - a transparency setting seems to be overriding the background.  Here are two screenshots - one with Chrome and one with Safari.  I double-checked that the latest version of celestial.js was loaded (not the old one).

<img width="671" alt="hemispherical_chrome" src="https://user-images.githubusercontent.com/5502468/61809997-3f00e100-ae36-11e9-8286-643fbbf93323.png">

<img width="671" alt="hemispherical_safari" src="https://user-images.githubusercontent.com/5502468/61810036-56d86500-ae36-11e9-9a27-5d8d870690c6.png">

**Comment by umutesen** [comment] 2020-02-01 01:15
Any updates on this?

**Comment by genghisken** [comment] 2020-02-01 01:49
I'd really love to be able to use these projections, but in astronomy we all use Macs, hence it's a non-starter at the moment.  It completely mystifies me that the other projections work fine, but not the spherical ones.

**Comment by ofrohn** [comment] 2020-02-02 20:27
OK so I´ve been able to reproduce the bug consistently. If seems to be that the background is reduced to a line along one meridian. And it also happens on other OSes under certain conditions, so I'll throw some grey matter at it and see what I can do!

**Comment by genghisken** [comment] 2020-02-02 22:33
Thanks!

**Comment by ofrohn** [comment] 2020-02-04 18:41
That may have been easier than expected. I gave the background 179.9 degrees radius so that it wraps neatly around everywhere — and it seems to work! I think that could be called the nuclear option, but anyway, can anybody verify if the issue is fixed in the newest version?

**Comment by umutesen** [comment] 2020-02-04 19:05
I can that confirm version 0.6.20 is working as expected in Safari (macOS Catalina 10.15). Thank you! 🥇

**Comment by genghisken** [comment] 2020-02-04 23:08
I can also confirm that it's working! Also Safari + MacOS Catalina 10.15.3.  Many thanks for fixing this - I can now allow my users to flip between aitoff and spherical projections!

**Comment by ofrohn** [comment] 2020-02-12 20:26
And now I found out that the above may not be necessary at all. The d3.geo has a nice property called graticule.outline that can be used to fill a background. It used to not work in clipped projection, but now it does. Could you check the latest release please to see if that s also the case with macOS?
If yes, I could probably make the projections with different clip angles transition smoothly.

**Comment by umutesen** [comment] 2020-02-12 21:11
It is working fine for me on 0.6.21 using Safari macOS Catalina.

Using `azimuthalEquidistant` it looks good but I guess the transition could be smoother :)

<img width="293" alt="Screenshot 2020-02-12 at 21 09 17" src="https://user-images.githubusercontent.com/4234033/74377528-fa419500-4ddb-11ea-9b1a-56383d3433a6.png">

**Comment by ofrohn** [comment] 2020-02-17 10:23
That's not the transition I was talking about. (prbly agree with you tho)

But the thing I was referring to, the animated transition between  projections with different clip angles, while now theoretically possible, still looks really weird, so I just leave it the way it is, since the animations are mostly just eye candy anyway.

**Closed by ofrohn** 2020-02-17 10:23 UTC
