### ISSUE TITLE
masOS Safari not filling and stroking map's outline correctly

### ISSUE THREAD

**Issue by JanisE** [ofrohn/d3-celestial#7] opened 2018-03-29 08:10 UTC
What is Safari's problem when drawing [the current sky by time and location](http://ofrohn.github.io/celestial-demo/location.html)?

`context.fill` [in `drawOutline`](https://github.com/ofrohn/d3-celestial/blob/master/src/celestial.js#L581) seems to have no affect, and `context.stroke` seems to draw a broken circle: 

http://storage5.static.itmages.com/i/18/0329/h_1522310479_5461621_65ecaba8c4.png

Tried with macOS Safari 10 and 11. On iPhone 8 it works all right though.

**Comment by csibivili** [comment] 2019-11-26 13:44
experiencing the same issue... 

https://trello-attachments.s3.amazonaws.com/5dd8184ccac55f7b03ea3343/1200x675/8b22bc3764f35159aef81c5e31f3e5ab/photo_2019-11-22_18.18.36.jpeg.jpg

**Comment by alexandervlpl** [comment] 2019-12-11 14:38
Yeah, this is a problem. iOS Safari is not affected, desktop only.

**Comment by knyazz** [comment] 2019-12-12 11:30
macOS Safari, the bug with the rendering of some projections:
https://armchairastronautics.blogspot.com/p/skymap.html
If we select some "...(hemi)" it renders something like that:
https://cloud.mail.ru/public/5BXX/32rgUxKXr

**Comment by ofrohn** [comment] 2020-02-02 20:30
I've finally been able to reproduce it. It also happens with other OSes, I'll get at soon...

**Comment by ofrohn** [comment] 2020-02-04 18:42
That may have been easier than expected. I gave the background 179.9 degrees radius so that it wraps neatly around everywhere — and it seems to work! I think that could be called the nuclear option, but anyway, can anybody verify if the issue is fixed in the newest version? (0.6.20)

**Comment by alexandervlpl** [comment] 2020-02-05 10:38
Nice hack. ;) This works for me on Safari, I tried many projections. Is there a chance that a 0.1° white sliver will now be visible on some high-res monitors? I don't see anything myself.

@ofrohn thanks for your work on this! Any way to contribute to development or buy you a beer?

**Comment by ofrohn** [comment] 2020-02-07 19:40
@alexandervlpl Thank you! I don't require any liquid fertilizer to work, but if you have any errors to report or feature ideas, you are always welcome! See the road map here: https://github.com/ofrohn/d3-celestial/wiki/Roadmap

The background is always centered before displaying, so the missing sliver should always be outside the clipped hemisphere.

**Closed** 2020-02-17 10:24 UTC
